source 'https://rubygems.org'
ruby '2.3.0'
gem 'rails', '>= 5.0.0.beta3', '< 5.1'
gem 'pg', '~> 0.18'
gem 'puma'

group :production do
  gem 'rails_12factor'
end

group :development, :test do
  gem 'byebug'
  gem 'dotenv-rails'
  gem 'factory_girl_rails'
  gem 'guard-rspec'
  gem 'rspec-activejob'
  gem 'rspec-rails'
  gem 'shoulda-matchers', '2.8.0', require: false
  # gem 'spring' # temporaly uncommented due to Rails5 is beta
  # gem 'spring-commands-rspec' # temporaly uncommented due to Rails5 is beta
  # gem 'spring-watcher-listen', '~> 2.0.0' # temporaly uncommented due to Rails5 is beta
end

group :development do
  gem 'annotate'
  gem 'better_errors'
  gem 'bullet'
  gem 'erb2haml' # run 'bundle exec rake haml:replace_erbs'
  gem 'listen', '~> 3.0.5'
  gem 'web-console', '~> 2.0'
end

group :test do
  gem 'capybara'
  # gem 'codeclimate-test-reporter', require: nil
  gem 'database_cleaner'
  gem 'faker'
  gem 'launchy'
  gem 'selenium-webdriver'
end

# Frontend
gem 'coffee-rails', '~> 4.1.0'
gem 'haml-rails'
gem 'jquery-rails'
gem 'sass-rails', '~> 5.0'
gem 'turbolinks', '~> 5.x'
gem 'uglifier', '>= 1.3.0'

# Miscellaneous stuffs
gem 'config'
gem 'fog-aws'
# gem 'friendly_id', '~> 5.1.0' # temporaly uncommented due to Rails5 is beta
gem 'jbuilder', '~> 2.0'
gem 'kaminari'
gem 'meta-tags'
gem 'paranoia', '~> 2.0'
gem 'seed-fu', '~> 2.3'
gem "sitemap_generator"
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

# ----------------------------------------------------------------
# Option Gems
# ----------------------------------------------------------------

# Background Job
# gem 'sidekiq'
# gem 'sinatra', require: false
# gem 'redis', '~>3.2'
# gem 'redis-namespace'

# Bootstrap
# gem 'bootstrap', '~> 4.0.0.alpha3'
# source 'https://rails-assets.org' do
#   gem 'rails-assets-tether', '>= 1.1.0'
# end

# Cancancan
# gem 'cancancan', '~> 1.10'

# Compass
# gem 'compass-rails'

# Devise
# gem 'bcrypt', '~> 3.1.7'
# gem 'devise'
# gem 'omniauth-facebook'
# gem 'omniauth-twitter'

# Exception Notification
# gem 'exception_notification'
# gem 'slack-notifier'

# Font Awesome
# gem 'font-awesome-rails'

# Paperclip
# gem 'paperclip', git: 'git://github.com/thoughtbot/paperclip.git'
# gem 'delayed_paperclip'
# gem 'aws-sdk'

# SNS API Wrapper
# gem 'koala', '~> 2.2'
# gem 'twitter'

# Socialization
# gem 'public_activity'
# gem 'socialization'
# gem 'unread'

# Miscellaneous stuffs
# gem 'active_link_to'
# gem "breadcrumbs_on_rails"
# gem "bower-rails", "~> 0.10.0"
# gem 'counter_culture', '~> 0.1.33'
# gem 'ransack'
# gem 'roadie-rails', '~> 1.0'
